---

- name: Configure celery
  template: >
    src=upstart.conf.j2
    dest=/etc/init/celery-{{item.action|default('worker')}}{{item.queue|default('') and ('-' + item.queue) or ''}}.conf
    owner=root group=root mode=0644
  with_items: celery_run
  notify: celery reload

- name: Prepare log directories
  file: state=directory dest={{item.log_dir|default(celery_log_dir)}} owner={{item.user|default(celery_user)}}
  with_items: celery_run

- name: Ensure celery services is started
  service: >
      name=celery-{{item.action|default('worker')}}{{item.queue|default('') and ('-' + item.queue) or ''}}
      state=started
      enabled=yes
  with_items: celery_run

# vim:sw=2:ft=ansible

