---

- name: Stop services
  service: state=stopped name=celery-{{item.action|default('worker')}}{{item.queue|default('') and ('-' + item.queue) or ''}}
  with_items: celery_run

- name: Delete configurations
  file: state=absent path=/etc/init/celery-{{item.action|default('worker')}}{{item.queue|default('') and ('-' + item.queue) or ''}}
  with_items: celery_run

- name: Delete logdirs
  file: state=absent dest={{item.log_dir|default(celery_log_dir)}}
  with_items: celery_run


# vim:sw=2:ft=ansible
